name: Docker Image CI

env:
  REGISTRY: ghcr.io
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  VERSION: 11

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  base_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      - name: downcase REPO
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            base
          tags: |
             type=raw,debian${{ env.VERSION }}
             
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build and export
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./debian${{ env.VERSION }}/base/
          outputs: type=docker,dest=/tmp/base.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: base
          path: /tmp/base.tar

  dependend_images:
    needs: base_image
    strategy:
      matrix:
        framework: [frr, p4, sdn]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      - name: downcase REPO
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: base
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/base.tar
          docker image ls -a

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ matrix.framework }}
          tags: |
             type=raw,debian${{ env.VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      
      - name: Build and load image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./debian${{ env.VERSION }}/${{ matrix.framework }}/
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE=base:debian${{ env.VERSION }}


      - name: Inspect Docker image
        run: docker image inspect $(docker image ls --filter "label=org.opencontainers.image.title=Docker-Images" -q)
